name: Linty
on:
  push:
  pull_request:

jobs:
  build:
    name: Linty
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: sonar
          restore-keys: sonar

      - name: Set Linty Analysis Parameters
        uses: haya14busa/action-cond@v1.2.1
        id: linty_analysis_parameters
        with:
          cond: ${{ github.event.pull_request.number != '' }}
          if_true: -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} -Dsonar.pullrequest.base=${{ github.base_ref }} -Dsonar.pullrequest.branch=${{ github.head_ref }}
          if_false: -Dsonar.branch.name=${GITHUB_REF#refs/*/}

      - name: Run Linty
        run: |
          docker run \
            -e SONAR_HOST_URL=https://cloud.linty-services.com \
            -e SONAR_TOKEN="${{ secrets.SCANNER_LINTY_SERVICES_CLOUD_TOKEN }}" \
            -e SONAR_SCANNER_OPTS="-Dsonar.qualitygate.wait=true ${{ steps.linty_analysis_parameters.outputs.value }}" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e GITHUB_REPOSITORY_OWNER="$GITHUB_REPOSITORY_OWNER" \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            -e TABBY_CAD_LICENSE="$TABBY_CAD_LICENSE" \
            -v "$PWD:/usr/src" \
            lintyservices/linty-scanner:cloud
        env:
          TABBY_CAD_LICENSE: ${{ secrets.TABBY_CAD_LICENSE }}

      - name: Debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: .linty/
          include-hidden-files: true
